// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SocialMedia.Api.Data;

#nullable disable

namespace SocialMedia.Api.Data.MySQLMigrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240625091152_InitialCreateMySqlDB")]
    partial class InitialCreateMySqlDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "f9b2e2a8-f455-4d27-87d7-6918cbc93c65",
                            ConcurrencyStamp = "1",
                            Name = "Admin",
                            NormalizedName = "Admin"
                        },
                        new
                        {
                            Id = "333e7b7b-9399-4ee9-8eaf-a92ef53cccdd",
                            ConcurrencyStamp = "2",
                            Name = "User",
                            NormalizedName = "User"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("SocialMedia.Api.Data.Models.ArchievedChat", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ChatId")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Chat Id");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("User Id");

                    b.HasKey("Id");

                    b.HasIndex("ChatId");

                    b.HasIndex("UserId", "ChatId")
                        .IsUnique();

                    b.ToTable("ArchievedChat");
                });

            modelBuilder.Entity("SocialMedia.Api.Data.Models.Authentication.SiteUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("AccountPolicyId")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Account Policy Id");

                    b.Property<string>("AccountPostPolicyId")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Account post Policy Id");

                    b.Property<string>("CommentPolicyId")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Comment Policy Id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Display Name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("Email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("First Name");

                    b.Property<string>("FriendListPolicyId")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Friend list Policy Id");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Last Name");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ReactPolicyId")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("React Policy Id");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("RefreshTokenExpiry")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("User Name");

                    b.HasKey("Id");

                    b.HasIndex("AccountPolicyId");

                    b.HasIndex("AccountPostPolicyId");

                    b.HasIndex("CommentPolicyId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("FriendListPolicyId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("ReactPolicyId");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("SocialMedia.Api.Data.Models.Block", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("BlockedUserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Blocked User Id");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("User Id");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "BlockedUserId")
                        .IsUnique();

                    b.ToTable("Blocks");
                });

            modelBuilder.Entity("SocialMedia.Api.Data.Models.Chat", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("CreatorId")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Creator Id");

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .HasColumnName("Description");

                    b.Property<string>("Name")
                        .HasColumnType("longtext")
                        .HasColumnName("Name");

                    b.Property<string>("PolicyId")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Chat Policy Id");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.HasIndex("PolicyId");

                    b.ToTable("Chat");
                });

            modelBuilder.Entity("SocialMedia.Api.Data.Models.ChatMember", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ChatId")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Chat Id");

                    b.Property<bool>("IsMember")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("MemberId")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Member 1 Id");

                    b.HasKey("Id");

                    b.HasIndex("ChatId");

                    b.HasIndex("MemberId", "ChatId")
                        .IsUnique();

                    b.ToTable("ChatMember");
                });

            modelBuilder.Entity("SocialMedia.Api.Data.Models.ChatMemberRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ChatMemberId")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Chat Member Id");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Role Id");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("ChatMemberId", "RoleId")
                        .IsUnique();

                    b.ToTable("ChatMemberRole");
                });

            modelBuilder.Entity("SocialMedia.Api.Data.Models.ChatMessage", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ChatId")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Chat Id");

                    b.Property<string>("Message")
                        .HasColumnType("longtext")
                        .HasColumnName("Message");

                    b.Property<string>("Photo")
                        .HasColumnType("longtext")
                        .HasColumnName("Photo");

                    b.Property<string>("SenderId")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Message Sender Id");

                    b.Property<DateTime>("SentAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("ChatId");

                    b.HasIndex("SenderId");

                    b.ToTable("ChatMessage", t =>
                        {
                            t.HasCheckConstraint("MessagePhotoCheck", "(Photo is NOT null AND Message is null) OR (Photo is null AND Message is NOT null) OR (Message is NOT null AND Photo is NOT null)");
                        });
                });

            modelBuilder.Entity("SocialMedia.Api.Data.Models.Follower", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FollowerId")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Follower Id");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("User Id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Followers");
                });

            modelBuilder.Entity("SocialMedia.Api.Data.Models.Friend", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FriendId")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Friend Id");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("User Id");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "FriendId")
                        .IsUnique();

                    b.ToTable("Friends");
                });

            modelBuilder.Entity("SocialMedia.Api.Data.Models.FriendRequest", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("IsAccepted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserWhoReceivedId")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Friend Request Person Id");

                    b.Property<string>("UserWhoSendId")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("User sended friend request Id");

                    b.HasKey("Id");

                    b.HasIndex("UserWhoSendId");

                    b.HasIndex("UserWhoReceivedId", "UserWhoSendId")
                        .IsUnique();

                    b.ToTable("FriendRequests");
                });

            modelBuilder.Entity("SocialMedia.Api.Data.Models.Group", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedUserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Group Creator Id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("GroupPolicyId")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Group Policy Id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedUserId");

                    b.HasIndex("GroupPolicyId");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("SocialMedia.Api.Data.Models.GroupAccessRequest", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("GroupId")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Group Id");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("User Id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("GroupId", "UserId")
                        .IsUnique();

                    b.ToTable("GroupAccessRequests");
                });

            modelBuilder.Entity("SocialMedia.Api.Data.Models.GroupMember", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("GroupId")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Group Id");

                    b.Property<string>("MemberId")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("User Id");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("MemberId", "GroupId")
                        .IsUnique();

                    b.ToTable("GroupMembers");
                });

            modelBuilder.Entity("SocialMedia.Api.Data.Models.GroupMemberRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("GroupMemberId")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Group Member Id");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Role Id");

                    b.HasKey("Id");

                    b.HasIndex("GroupMemberId");

                    b.HasIndex("RoleId", "GroupMemberId")
                        .IsUnique();

                    b.ToTable("GroupMemberRoles");
                });

            modelBuilder.Entity("SocialMedia.Api.Data.Models.GroupPost", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("GroupId")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Group Id");

                    b.Property<string>("PostId")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Post Id");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("User Id");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId");

                    b.ToTable("GroupPosts");
                });

            modelBuilder.Entity("SocialMedia.Api.Data.Models.MessageReact", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("MessageId")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Message Id");

                    b.Property<string>("ReactId")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("React Id");

                    b.Property<string>("ReactedUserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Reacted User Id");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ReactId");

                    b.HasIndex("MessageId", "ReactedUserId")
                        .IsUnique();

                    b.HasIndex("ReactedUserId", "MessageId")
                        .IsUnique();

                    b.ToTable("MessageReact");
                });

            modelBuilder.Entity("SocialMedia.Api.Data.Models.Page", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.ToTable("Pages");
                });

            modelBuilder.Entity("SocialMedia.Api.Data.Models.PageFollower", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FollowerId")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Follower Id");

                    b.Property<string>("PageId")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Page Id");

                    b.HasKey("Id");

                    b.HasIndex("FollowerId");

                    b.HasIndex("PageId", "FollowerId")
                        .IsUnique();

                    b.ToTable("PageFollowers");
                });

            modelBuilder.Entity("SocialMedia.Api.Data.Models.PagePost", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PageId")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Page Id");

                    b.Property<string>("PostId")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Post Id");

                    b.HasKey("Id");

                    b.HasIndex("PageId");

                    b.HasIndex("PostId");

                    b.ToTable("PagePosts");
                });

            modelBuilder.Entity("SocialMedia.Api.Data.Models.Policy", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PolicyType")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Policy Type");

                    b.HasKey("Id");

                    b.HasIndex("PolicyType")
                        .IsUnique();

                    b.ToTable("Policies");
                });

            modelBuilder.Entity("SocialMedia.Api.Data.Models.Post", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("CommentPolicyId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Post content");

                    b.Property<string>("PostPolicyId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("PostedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("Posted At Date");

                    b.Property<string>("ReactPolicyId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("Post Update Date");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("CommentPolicyId");

                    b.HasIndex("PostPolicyId");

                    b.HasIndex("ReactPolicyId");

                    b.HasIndex("UserId");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("SocialMedia.Api.Data.Models.PostComment", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("CommentId")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Base Comment Id");

                    b.Property<string>("CommentImage")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PostId")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Post Id");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("User Id");

                    b.HasKey("Id");

                    b.HasIndex("CommentId");

                    b.HasIndex("CommentImage")
                        .IsUnique();

                    b.HasIndex("PostId");

                    b.HasIndex("UserId");

                    b.ToTable("PostComments");
                });

            modelBuilder.Entity("SocialMedia.Api.Data.Models.PostImages", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Image Url");

                    b.Property<string>("PostId")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Post Id");

                    b.HasKey("Id");

                    b.HasIndex("ImageUrl")
                        .IsUnique();

                    b.HasIndex("PostId");

                    b.ToTable("PostImages");
                });

            modelBuilder.Entity("SocialMedia.Api.Data.Models.PostReacts", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PostId")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Post Id");

                    b.Property<string>("PostReactId")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Post React Id");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("User Id");

                    b.HasKey("Id");

                    b.HasIndex("PostReactId");

                    b.HasIndex("UserId");

                    b.HasIndex("PostId", "UserId")
                        .IsUnique();

                    b.ToTable("PostReacts");
                });

            modelBuilder.Entity("SocialMedia.Api.Data.Models.PostView", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PostId")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Post Id");

                    b.Property<int>("ViewNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("Post view number");

                    b.HasKey("Id");

                    b.HasIndex("PostId")
                        .IsUnique();

                    b.ToTable("PostViews");
                });

            modelBuilder.Entity("SocialMedia.Api.Data.Models.PrivateChat", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ChatId")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Chat Id");

                    b.Property<bool>("IsAccepted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsBlockedByUser1")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsBlockedByUser2")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("User1Id")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("User 1 Id");

                    b.Property<string>("User2Id")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("User 2 Id");

                    b.HasKey("Id");

                    b.HasIndex("ChatId");

                    b.HasIndex("User1Id", "ChatId")
                        .IsUnique();

                    b.HasIndex("User1Id", "User2Id")
                        .IsUnique();

                    b.HasIndex("User2Id", "ChatId")
                        .IsUnique();

                    b.ToTable("PrivateChat");
                });

            modelBuilder.Entity("SocialMedia.Api.Data.Models.React", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ReactValue")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("React Value");

                    b.HasKey("Id");

                    b.HasIndex("ReactValue")
                        .IsUnique();

                    b.ToTable("Reacts");
                });

            modelBuilder.Entity("SocialMedia.Api.Data.Models.Role", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleName")
                        .IsUnique();

                    b.ToTable("Role");
                });

            modelBuilder.Entity("SocialMedia.Api.Data.Models.SarehneMessage", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("Message");

                    b.Property<string>("MessagePolicyId")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Message Policy Id");

                    b.Property<string>("ReceiverId")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Receiver Id");

                    b.Property<string>("SenderName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("longtext")
                        .HasDefaultValue("Anonymous");

                    b.Property<DateTime>("SentAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("getdate()");

                    b.HasKey("Id");

                    b.HasIndex("MessagePolicyId");

                    b.HasIndex("ReceiverId");

                    b.ToTable("SarehneMessages");
                });

            modelBuilder.Entity("SocialMedia.Api.Data.Models.SavedPosts", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FolderId")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Folder Id");

                    b.Property<string>("PostId")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Post Id");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("User Id");

                    b.HasKey("Id");

                    b.HasIndex("FolderId");

                    b.HasIndex("UserId");

                    b.HasIndex("PostId", "FolderId")
                        .IsUnique();

                    b.ToTable("SavedPosts");
                });

            modelBuilder.Entity("SocialMedia.Api.Data.Models.UserSavedPostsFolders", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FolderName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("Folder Name");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("User Id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("FolderName", "UserId")
                        .IsUnique();

                    b.ToTable("UserSavedPostsFolders");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("SocialMedia.Api.Data.Models.Authentication.SiteUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("SocialMedia.Api.Data.Models.Authentication.SiteUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SocialMedia.Api.Data.Models.Authentication.SiteUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("SocialMedia.Api.Data.Models.Authentication.SiteUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SocialMedia.Api.Data.Models.ArchievedChat", b =>
                {
                    b.HasOne("SocialMedia.Api.Data.Models.Chat", "Chat")
                        .WithMany("ArchievedChats")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SocialMedia.Api.Data.Models.Authentication.SiteUser", "User")
                        .WithMany("ArchievedChats")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chat");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SocialMedia.Api.Data.Models.Authentication.SiteUser", b =>
                {
                    b.HasOne("SocialMedia.Api.Data.Models.Policy", "AccountPolicy")
                        .WithMany("UserAccountPolicies")
                        .HasForeignKey("AccountPolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SocialMedia.Api.Data.Models.Policy", "PostPolicy")
                        .WithMany("UserPostPolicies")
                        .HasForeignKey("AccountPostPolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SocialMedia.Api.Data.Models.Policy", "CommentPolicy")
                        .WithMany("UserCommentPolicies")
                        .HasForeignKey("CommentPolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SocialMedia.Api.Data.Models.Policy", "FriendListPolicy")
                        .WithMany("UserFriendListPolicies")
                        .HasForeignKey("FriendListPolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SocialMedia.Api.Data.Models.Policy", "ReactPolicy")
                        .WithMany("UserReactPolicies")
                        .HasForeignKey("ReactPolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccountPolicy");

                    b.Navigation("CommentPolicy");

                    b.Navigation("FriendListPolicy");

                    b.Navigation("PostPolicy");

                    b.Navigation("ReactPolicy");
                });

            modelBuilder.Entity("SocialMedia.Api.Data.Models.Block", b =>
                {
                    b.HasOne("SocialMedia.Api.Data.Models.Authentication.SiteUser", "User")
                        .WithMany("Blocks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SocialMedia.Api.Data.Models.Chat", b =>
                {
                    b.HasOne("SocialMedia.Api.Data.Models.Authentication.SiteUser", "User")
                        .WithMany("Chats")
                        .HasForeignKey("CreatorId");

                    b.HasOne("SocialMedia.Api.Data.Models.Policy", "Policy")
                        .WithMany("Chats")
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Policy");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SocialMedia.Api.Data.Models.ChatMember", b =>
                {
                    b.HasOne("SocialMedia.Api.Data.Models.Chat", "Chat")
                        .WithMany("ChatMembers")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SocialMedia.Api.Data.Models.Authentication.SiteUser", "User")
                        .WithMany("ChatMembers1")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chat");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SocialMedia.Api.Data.Models.ChatMemberRole", b =>
                {
                    b.HasOne("SocialMedia.Api.Data.Models.ChatMember", "ChatMember")
                        .WithMany("ChatMemberRoles")
                        .HasForeignKey("ChatMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SocialMedia.Api.Data.Models.Role", "Role")
                        .WithMany("ChatMemberRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChatMember");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("SocialMedia.Api.Data.Models.ChatMessage", b =>
                {
                    b.HasOne("SocialMedia.Api.Data.Models.Chat", "Chat")
                        .WithMany("ChatMessages")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SocialMedia.Api.Data.Models.Authentication.SiteUser", "User")
                        .WithMany("ChatMessages")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Chat");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SocialMedia.Api.Data.Models.Follower", b =>
                {
                    b.HasOne("SocialMedia.Api.Data.Models.Authentication.SiteUser", "User")
                        .WithMany("Followers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SocialMedia.Api.Data.Models.Friend", b =>
                {
                    b.HasOne("SocialMedia.Api.Data.Models.Authentication.SiteUser", "User")
                        .WithMany("Friends")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SocialMedia.Api.Data.Models.FriendRequest", b =>
                {
                    b.HasOne("SocialMedia.Api.Data.Models.Authentication.SiteUser", "User")
                        .WithMany("FriendRequests")
                        .HasForeignKey("UserWhoSendId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SocialMedia.Api.Data.Models.Group", b =>
                {
                    b.HasOne("SocialMedia.Api.Data.Models.Authentication.SiteUser", "User")
                        .WithMany("Groups")
                        .HasForeignKey("CreatedUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SocialMedia.Api.Data.Models.Policy", "GroupPolicy")
                        .WithMany("GroupPolicies")
                        .HasForeignKey("GroupPolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GroupPolicy");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SocialMedia.Api.Data.Models.GroupAccessRequest", b =>
                {
                    b.HasOne("SocialMedia.Api.Data.Models.Group", "Group")
                        .WithMany("GroupAccessRequests")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SocialMedia.Api.Data.Models.Authentication.SiteUser", "User")
                        .WithMany("GroupAccessRequests")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SocialMedia.Api.Data.Models.GroupMember", b =>
                {
                    b.HasOne("SocialMedia.Api.Data.Models.Group", "Group")
                        .WithMany("GroupMembers")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SocialMedia.Api.Data.Models.Authentication.SiteUser", "User")
                        .WithMany("GroupMembers")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SocialMedia.Api.Data.Models.GroupMemberRole", b =>
                {
                    b.HasOne("SocialMedia.Api.Data.Models.GroupMember", "GroupMember")
                        .WithMany("GroupMemberRoles")
                        .HasForeignKey("GroupMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SocialMedia.Api.Data.Models.Role", "GroupRole")
                        .WithMany("GroupMemberRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GroupMember");

                    b.Navigation("GroupRole");
                });

            modelBuilder.Entity("SocialMedia.Api.Data.Models.GroupPost", b =>
                {
                    b.HasOne("SocialMedia.Api.Data.Models.Group", "Group")
                        .WithMany("GroupPosts")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SocialMedia.Api.Data.Models.Post", "Post")
                        .WithMany("GroupPosts")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SocialMedia.Api.Data.Models.Authentication.SiteUser", "User")
                        .WithMany("GroupPosts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SocialMedia.Api.Data.Models.MessageReact", b =>
                {
                    b.HasOne("SocialMedia.Api.Data.Models.ChatMessage", "Message")
                        .WithMany("MessageReacts")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SocialMedia.Api.Data.Models.React", "React")
                        .WithMany("MessageReacts")
                        .HasForeignKey("ReactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SocialMedia.Api.Data.Models.Authentication.SiteUser", "User")
                        .WithMany("MessageReacts")
                        .HasForeignKey("ReactedUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Message");

                    b.Navigation("React");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SocialMedia.Api.Data.Models.Page", b =>
                {
                    b.HasOne("SocialMedia.Api.Data.Models.Authentication.SiteUser", "Creator")
                        .WithMany("Pages")
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("SocialMedia.Api.Data.Models.PageFollower", b =>
                {
                    b.HasOne("SocialMedia.Api.Data.Models.Authentication.SiteUser", "User")
                        .WithMany("PageFollowers")
                        .HasForeignKey("FollowerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SocialMedia.Api.Data.Models.Page", "Page")
                        .WithMany("PageFollowers")
                        .HasForeignKey("PageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Page");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SocialMedia.Api.Data.Models.PagePost", b =>
                {
                    b.HasOne("SocialMedia.Api.Data.Models.Page", "Page")
                        .WithMany("PagePosts")
                        .HasForeignKey("PageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SocialMedia.Api.Data.Models.Post", "Post")
                        .WithMany("PagePosts")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Page");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("SocialMedia.Api.Data.Models.Post", b =>
                {
                    b.HasOne("SocialMedia.Api.Data.Models.Policy", "CommentPolicy")
                        .WithMany("CommentPolicies")
                        .HasForeignKey("CommentPolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SocialMedia.Api.Data.Models.Policy", "PostPolicy")
                        .WithMany("PostPolicies")
                        .HasForeignKey("PostPolicyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SocialMedia.Api.Data.Models.Policy", "ReactPolicy")
                        .WithMany("ReactPolicies")
                        .HasForeignKey("ReactPolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SocialMedia.Api.Data.Models.Authentication.SiteUser", "User")
                        .WithMany("Posts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CommentPolicy");

                    b.Navigation("PostPolicy");

                    b.Navigation("ReactPolicy");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SocialMedia.Api.Data.Models.PostComment", b =>
                {
                    b.HasOne("SocialMedia.Api.Data.Models.PostComment", "BaseComment")
                        .WithMany("Replays")
                        .HasForeignKey("CommentId");

                    b.HasOne("SocialMedia.Api.Data.Models.Post", "Post")
                        .WithMany("PostComments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SocialMedia.Api.Data.Models.Authentication.SiteUser", "User")
                        .WithMany("PostComments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BaseComment");

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SocialMedia.Api.Data.Models.PostImages", b =>
                {
                    b.HasOne("SocialMedia.Api.Data.Models.Post", "Post")
                        .WithMany("PostImages")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");
                });

            modelBuilder.Entity("SocialMedia.Api.Data.Models.PostReacts", b =>
                {
                    b.HasOne("SocialMedia.Api.Data.Models.Post", "Post")
                        .WithMany("PostReacts")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SocialMedia.Api.Data.Models.React", "React")
                        .WithMany("PostReacts")
                        .HasForeignKey("PostReactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SocialMedia.Api.Data.Models.Authentication.SiteUser", "User")
                        .WithMany("PostReacts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("React");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SocialMedia.Api.Data.Models.PostView", b =>
                {
                    b.HasOne("SocialMedia.Api.Data.Models.Post", "Post")
                        .WithMany("PostViews")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");
                });

            modelBuilder.Entity("SocialMedia.Api.Data.Models.PrivateChat", b =>
                {
                    b.HasOne("SocialMedia.Api.Data.Models.Chat", "Chat")
                        .WithMany("PrivateChats")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SocialMedia.Api.Data.Models.Authentication.SiteUser", "User1")
                        .WithMany("PrivateChats1")
                        .HasForeignKey("User1Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SocialMedia.Api.Data.Models.Authentication.SiteUser", "User2")
                        .WithMany("PrivateChats2")
                        .HasForeignKey("User2Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Chat");

                    b.Navigation("User1");

                    b.Navigation("User2");
                });

            modelBuilder.Entity("SocialMedia.Api.Data.Models.SarehneMessage", b =>
                {
                    b.HasOne("SocialMedia.Api.Data.Models.Policy", "SarehneMessagePolicy")
                        .WithMany("SarehneMessagePolicies")
                        .HasForeignKey("MessagePolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SocialMedia.Api.Data.Models.Authentication.SiteUser", "User")
                        .WithMany("SarehneMessages")
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SarehneMessagePolicy");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SocialMedia.Api.Data.Models.SavedPosts", b =>
                {
                    b.HasOne("SocialMedia.Api.Data.Models.UserSavedPostsFolders", "UserSavedPostsFolder")
                        .WithMany("SavedPosts")
                        .HasForeignKey("FolderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SocialMedia.Api.Data.Models.Post", "Post")
                        .WithMany("SavedPosts")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SocialMedia.Api.Data.Models.Authentication.SiteUser", "User")
                        .WithMany("SavedPosts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("User");

                    b.Navigation("UserSavedPostsFolder");
                });

            modelBuilder.Entity("SocialMedia.Api.Data.Models.UserSavedPostsFolders", b =>
                {
                    b.HasOne("SocialMedia.Api.Data.Models.Authentication.SiteUser", "User")
                        .WithMany("UserSavedPostsFolders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SocialMedia.Api.Data.Models.Authentication.SiteUser", b =>
                {
                    b.Navigation("ArchievedChats");

                    b.Navigation("Blocks");

                    b.Navigation("ChatMembers1");

                    b.Navigation("ChatMessages");

                    b.Navigation("Chats");

                    b.Navigation("Followers");

                    b.Navigation("FriendRequests");

                    b.Navigation("Friends");

                    b.Navigation("GroupAccessRequests");

                    b.Navigation("GroupMembers");

                    b.Navigation("GroupPosts");

                    b.Navigation("Groups");

                    b.Navigation("MessageReacts");

                    b.Navigation("PageFollowers");

                    b.Navigation("Pages");

                    b.Navigation("PostComments");

                    b.Navigation("PostReacts");

                    b.Navigation("Posts");

                    b.Navigation("PrivateChats1");

                    b.Navigation("PrivateChats2");

                    b.Navigation("SarehneMessages");

                    b.Navigation("SavedPosts");

                    b.Navigation("UserSavedPostsFolders");
                });

            modelBuilder.Entity("SocialMedia.Api.Data.Models.Chat", b =>
                {
                    b.Navigation("ArchievedChats");

                    b.Navigation("ChatMembers");

                    b.Navigation("ChatMessages");

                    b.Navigation("PrivateChats");
                });

            modelBuilder.Entity("SocialMedia.Api.Data.Models.ChatMember", b =>
                {
                    b.Navigation("ChatMemberRoles");
                });

            modelBuilder.Entity("SocialMedia.Api.Data.Models.ChatMessage", b =>
                {
                    b.Navigation("MessageReacts");
                });

            modelBuilder.Entity("SocialMedia.Api.Data.Models.Group", b =>
                {
                    b.Navigation("GroupAccessRequests");

                    b.Navigation("GroupMembers");

                    b.Navigation("GroupPosts");
                });

            modelBuilder.Entity("SocialMedia.Api.Data.Models.GroupMember", b =>
                {
                    b.Navigation("GroupMemberRoles");
                });

            modelBuilder.Entity("SocialMedia.Api.Data.Models.Page", b =>
                {
                    b.Navigation("PageFollowers");

                    b.Navigation("PagePosts");
                });

            modelBuilder.Entity("SocialMedia.Api.Data.Models.Policy", b =>
                {
                    b.Navigation("Chats");

                    b.Navigation("CommentPolicies");

                    b.Navigation("GroupPolicies");

                    b.Navigation("PostPolicies");

                    b.Navigation("ReactPolicies");

                    b.Navigation("SarehneMessagePolicies");

                    b.Navigation("UserAccountPolicies");

                    b.Navigation("UserCommentPolicies");

                    b.Navigation("UserFriendListPolicies");

                    b.Navigation("UserPostPolicies");

                    b.Navigation("UserReactPolicies");
                });

            modelBuilder.Entity("SocialMedia.Api.Data.Models.Post", b =>
                {
                    b.Navigation("GroupPosts");

                    b.Navigation("PagePosts");

                    b.Navigation("PostComments");

                    b.Navigation("PostImages");

                    b.Navigation("PostReacts");

                    b.Navigation("PostViews");

                    b.Navigation("SavedPosts");
                });

            modelBuilder.Entity("SocialMedia.Api.Data.Models.PostComment", b =>
                {
                    b.Navigation("Replays");
                });

            modelBuilder.Entity("SocialMedia.Api.Data.Models.React", b =>
                {
                    b.Navigation("MessageReacts");

                    b.Navigation("PostReacts");
                });

            modelBuilder.Entity("SocialMedia.Api.Data.Models.Role", b =>
                {
                    b.Navigation("ChatMemberRoles");

                    b.Navigation("GroupMemberRoles");
                });

            modelBuilder.Entity("SocialMedia.Api.Data.Models.UserSavedPostsFolders", b =>
                {
                    b.Navigation("SavedPosts");
                });
#pragma warning restore 612, 618
        }
    }
}
