// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SocialMedia.Data;

#nullable disable

namespace SocialMedia.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("SocialMedia.Data.Models.AccountPolicy", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PolicyId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Policy Id");

                    b.HasKey("Id");

                    b.HasIndex("PolicyId")
                        .IsUnique();

                    b.ToTable("AccountPolicies");
                });

            modelBuilder.Entity("SocialMedia.Data.Models.AccountPostsPolicy", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PolicyId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Policy Id");

                    b.HasKey("Id");

                    b.HasIndex("PolicyId")
                        .IsUnique();

                    b.ToTable("PostPolicies");
                });

            modelBuilder.Entity("SocialMedia.Data.Models.Authentication.SiteUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("AccountPolicyId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Account Policy Id");

                    b.Property<string>("AccountPostPolicyId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Account post Policy Id");

                    b.Property<string>("CommentPolicyId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Comment Policy Id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Display Name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("Email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("First Name");

                    b.Property<string>("FriendListPolicyId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Friend list Policy Id");

                    b.Property<bool>("IsFriendListPrivate")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Last Name");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("ReactPolicyId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("React Policy Id");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("User Name");

                    b.HasKey("Id");

                    b.HasIndex("AccountPolicyId");

                    b.HasIndex("AccountPostPolicyId");

                    b.HasIndex("CommentPolicyId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("FriendListPolicyId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("ReactPolicyId");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("SocialMedia.Data.Models.Block", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BlockedUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Blocked User Id");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("User Id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Blocks");
                });

            modelBuilder.Entity("SocialMedia.Data.Models.CommentPolicy", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PolicyId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Policy Id");

                    b.HasKey("Id");

                    b.HasIndex("PolicyId")
                        .IsUnique();

                    b.ToTable("CommentPolicies");
                });

            modelBuilder.Entity("SocialMedia.Data.Models.Follower", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FollowerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Follower Id");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("User Id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Followers");
                });

            modelBuilder.Entity("SocialMedia.Data.Models.Friend", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FriendId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Friend Id");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("User Id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Friends");
                });

            modelBuilder.Entity("SocialMedia.Data.Models.FriendListPolicy", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PolicyId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Policy Id");

                    b.HasKey("Id");

                    b.HasIndex("PolicyId")
                        .IsUnique();

                    b.ToTable("FriendListPolicies");
                });

            modelBuilder.Entity("SocialMedia.Data.Models.FriendRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsAccepted")
                        .HasColumnType("bit");

                    b.Property<string>("UserWhoReceivedId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Friend Request Person Id");

                    b.Property<string>("UserWhoSendId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("User sended friend request Id");

                    b.HasKey("Id");

                    b.HasIndex("UserWhoReceivedId")
                        .IsUnique();

                    b.HasIndex("UserWhoSendId");

                    b.ToTable("FriendRequests");
                });

            modelBuilder.Entity("SocialMedia.Data.Models.Policy", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PolicyType")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Policy Type");

                    b.HasKey("Id");

                    b.HasIndex("PolicyType")
                        .IsUnique();

                    b.ToTable("Policies");
                });

            modelBuilder.Entity("SocialMedia.Data.Models.Post", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CommentPolicyId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Comment Policy Id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Post content");

                    b.Property<string>("PolicyId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Policy Id");

                    b.Property<DateTime>("PostedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("Post Date");

                    b.Property<string>("ReactPolicyId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("React Policy Id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("Post Update Date");

                    b.HasKey("Id");

                    b.HasIndex("CommentPolicyId");

                    b.HasIndex("PolicyId");

                    b.HasIndex("ReactPolicyId");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("SocialMedia.Data.Models.PostComments", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("CommentImage")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PostId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Post Id");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("User Id");

                    b.HasKey("Id");

                    b.HasIndex("CommentImage")
                        .IsUnique()
                        .HasFilter("[CommentImage] IS NOT NULL");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId");

                    b.ToTable("PostComments");
                });

            modelBuilder.Entity("SocialMedia.Data.Models.PostImages", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Image Url");

                    b.Property<string>("PostId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Post Id");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.ToTable("PostImages");
                });

            modelBuilder.Entity("SocialMedia.Data.Models.PostReacts", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PostId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Post Id");

                    b.Property<string>("ReactId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("React Id");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("User Id");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.HasIndex("ReactId");

                    b.HasIndex("UserId");

                    b.ToTable("PostReacts");
                });

            modelBuilder.Entity("SocialMedia.Data.Models.PostView", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PostId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Post Id");

                    b.Property<int>("ViewNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("Post view number");

                    b.HasKey("Id");

                    b.HasIndex("PostId")
                        .IsUnique();

                    b.ToTable("PostViews");
                });

            modelBuilder.Entity("SocialMedia.Data.Models.React", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ReactValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("React Value");

                    b.HasKey("Id");

                    b.ToTable("Reacts");
                });

            modelBuilder.Entity("SocialMedia.Data.Models.ReactPolicy", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PolicyId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Policy Id");

                    b.HasKey("Id");

                    b.HasIndex("PolicyId")
                        .IsUnique();

                    b.ToTable("ReactPolicies");
                });

            modelBuilder.Entity("SocialMedia.Data.Models.SavedPosts", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FolderId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Folder Id");

                    b.Property<string>("PostId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Post Id");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("User Id");

                    b.HasKey("Id");

                    b.HasIndex("FolderId");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId");

                    b.ToTable("SavedPosts");
                });

            modelBuilder.Entity("SocialMedia.Data.Models.SpecialCommentReacts", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ReactId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("React Id");

                    b.HasKey("Id");

                    b.HasIndex("ReactId")
                        .IsUnique();

                    b.ToTable("SpecialCommentReacts");
                });

            modelBuilder.Entity("SocialMedia.Data.Models.SpecialPostReacts", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ReactId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("React Id");

                    b.HasKey("Id");

                    b.HasIndex("ReactId")
                        .IsUnique();

                    b.ToTable("SpecialPostReacts");
                });

            modelBuilder.Entity("SocialMedia.Data.Models.UserPosts", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PostId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Post Id");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("User Id");

                    b.HasKey("Id");

                    b.HasIndex("PostId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("UserPosts");
                });

            modelBuilder.Entity("SocialMedia.Data.Models.UserSavedPostsFolders", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FolderName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Folder Name");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("User Id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserSavedPostsFolders");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("SocialMedia.Data.Models.Authentication.SiteUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("SocialMedia.Data.Models.Authentication.SiteUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SocialMedia.Data.Models.Authentication.SiteUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("SocialMedia.Data.Models.Authentication.SiteUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SocialMedia.Data.Models.AccountPolicy", b =>
                {
                    b.HasOne("SocialMedia.Data.Models.Policy", "Policy")
                        .WithMany("AccountPolicies")
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Policy");
                });

            modelBuilder.Entity("SocialMedia.Data.Models.AccountPostsPolicy", b =>
                {
                    b.HasOne("SocialMedia.Data.Models.Policy", "Policy")
                        .WithMany("PostPolicies")
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Policy");
                });

            modelBuilder.Entity("SocialMedia.Data.Models.Authentication.SiteUser", b =>
                {
                    b.HasOne("SocialMedia.Data.Models.AccountPolicy", "AccountPolicy")
                        .WithMany("Users")
                        .HasForeignKey("AccountPolicyId");

                    b.HasOne("SocialMedia.Data.Models.AccountPostsPolicy", "PostPolicy")
                        .WithMany("Users")
                        .HasForeignKey("AccountPostPolicyId");

                    b.HasOne("SocialMedia.Data.Models.CommentPolicy", "CommentPolicy")
                        .WithMany("Users")
                        .HasForeignKey("CommentPolicyId");

                    b.HasOne("SocialMedia.Data.Models.FriendListPolicy", "FriendListPolicy")
                        .WithMany("Users")
                        .HasForeignKey("FriendListPolicyId");

                    b.HasOne("SocialMedia.Data.Models.ReactPolicy", "ReactPolicy")
                        .WithMany("Users")
                        .HasForeignKey("ReactPolicyId");

                    b.Navigation("AccountPolicy");

                    b.Navigation("CommentPolicy");

                    b.Navigation("FriendListPolicy");

                    b.Navigation("PostPolicy");

                    b.Navigation("ReactPolicy");
                });

            modelBuilder.Entity("SocialMedia.Data.Models.Block", b =>
                {
                    b.HasOne("SocialMedia.Data.Models.Authentication.SiteUser", "User")
                        .WithMany("Blocks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SocialMedia.Data.Models.CommentPolicy", b =>
                {
                    b.HasOne("SocialMedia.Data.Models.Policy", "Policy")
                        .WithMany("CommentPolicies")
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Policy");
                });

            modelBuilder.Entity("SocialMedia.Data.Models.Follower", b =>
                {
                    b.HasOne("SocialMedia.Data.Models.Authentication.SiteUser", "User")
                        .WithMany("Followers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SocialMedia.Data.Models.Friend", b =>
                {
                    b.HasOne("SocialMedia.Data.Models.Authentication.SiteUser", "User")
                        .WithMany("Friends")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SocialMedia.Data.Models.FriendListPolicy", b =>
                {
                    b.HasOne("SocialMedia.Data.Models.Policy", "Policy")
                        .WithMany("FriendListPolicies")
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Policy");
                });

            modelBuilder.Entity("SocialMedia.Data.Models.FriendRequest", b =>
                {
                    b.HasOne("SocialMedia.Data.Models.Authentication.SiteUser", "User")
                        .WithMany("FriendRequests")
                        .HasForeignKey("UserWhoSendId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SocialMedia.Data.Models.Post", b =>
                {
                    b.HasOne("SocialMedia.Data.Models.CommentPolicy", "CommentPolicy")
                        .WithMany("Posts")
                        .HasForeignKey("CommentPolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SocialMedia.Data.Models.Policy", "Policy")
                        .WithMany("Posts")
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SocialMedia.Data.Models.ReactPolicy", "ReactPolicy")
                        .WithMany("Posts")
                        .HasForeignKey("ReactPolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CommentPolicy");

                    b.Navigation("Policy");

                    b.Navigation("ReactPolicy");
                });

            modelBuilder.Entity("SocialMedia.Data.Models.PostComments", b =>
                {
                    b.HasOne("SocialMedia.Data.Models.Post", "Post")
                        .WithMany("PostComments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SocialMedia.Data.Models.Authentication.SiteUser", "User")
                        .WithMany("PostComments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SocialMedia.Data.Models.PostImages", b =>
                {
                    b.HasOne("SocialMedia.Data.Models.Post", "Post")
                        .WithMany("PostImages")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");
                });

            modelBuilder.Entity("SocialMedia.Data.Models.PostReacts", b =>
                {
                    b.HasOne("SocialMedia.Data.Models.Post", "Post")
                        .WithMany("PostReacts")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SocialMedia.Data.Models.React", "React")
                        .WithMany("PostReacts")
                        .HasForeignKey("ReactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SocialMedia.Data.Models.Authentication.SiteUser", "User")
                        .WithMany("PostReacts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("React");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SocialMedia.Data.Models.PostView", b =>
                {
                    b.HasOne("SocialMedia.Data.Models.Post", "Post")
                        .WithMany("PostViews")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");
                });

            modelBuilder.Entity("SocialMedia.Data.Models.ReactPolicy", b =>
                {
                    b.HasOne("SocialMedia.Data.Models.Policy", "Policy")
                        .WithMany("ReactPolicies")
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Policy");
                });

            modelBuilder.Entity("SocialMedia.Data.Models.SavedPosts", b =>
                {
                    b.HasOne("SocialMedia.Data.Models.UserSavedPostsFolders", "UserSavedPostsFolder")
                        .WithMany("SavedPosts")
                        .HasForeignKey("FolderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SocialMedia.Data.Models.Post", "Post")
                        .WithMany("SavedPosts")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SocialMedia.Data.Models.Authentication.SiteUser", "User")
                        .WithMany("SavedPosts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("User");

                    b.Navigation("UserSavedPostsFolder");
                });

            modelBuilder.Entity("SocialMedia.Data.Models.SpecialCommentReacts", b =>
                {
                    b.HasOne("SocialMedia.Data.Models.React", "React")
                        .WithMany("SpecialCommentReacts")
                        .HasForeignKey("ReactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("React");
                });

            modelBuilder.Entity("SocialMedia.Data.Models.SpecialPostReacts", b =>
                {
                    b.HasOne("SocialMedia.Data.Models.React", "React")
                        .WithMany("SpecialPostReacts")
                        .HasForeignKey("ReactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("React");
                });

            modelBuilder.Entity("SocialMedia.Data.Models.UserPosts", b =>
                {
                    b.HasOne("SocialMedia.Data.Models.Post", "Post")
                        .WithMany("UserPosts")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SocialMedia.Data.Models.Authentication.SiteUser", "User")
                        .WithMany("UserPosts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SocialMedia.Data.Models.UserSavedPostsFolders", b =>
                {
                    b.HasOne("SocialMedia.Data.Models.Authentication.SiteUser", "User")
                        .WithMany("UserSavedPostsFolders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SocialMedia.Data.Models.AccountPolicy", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("SocialMedia.Data.Models.AccountPostsPolicy", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("SocialMedia.Data.Models.Authentication.SiteUser", b =>
                {
                    b.Navigation("Blocks");

                    b.Navigation("Followers");

                    b.Navigation("FriendRequests");

                    b.Navigation("Friends");

                    b.Navigation("PostComments");

                    b.Navigation("PostReacts");

                    b.Navigation("SavedPosts");

                    b.Navigation("UserPosts");

                    b.Navigation("UserSavedPostsFolders");
                });

            modelBuilder.Entity("SocialMedia.Data.Models.CommentPolicy", b =>
                {
                    b.Navigation("Posts");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("SocialMedia.Data.Models.FriendListPolicy", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("SocialMedia.Data.Models.Policy", b =>
                {
                    b.Navigation("AccountPolicies");

                    b.Navigation("CommentPolicies");

                    b.Navigation("FriendListPolicies");

                    b.Navigation("PostPolicies");

                    b.Navigation("Posts");

                    b.Navigation("ReactPolicies");
                });

            modelBuilder.Entity("SocialMedia.Data.Models.Post", b =>
                {
                    b.Navigation("PostComments");

                    b.Navigation("PostImages");

                    b.Navigation("PostReacts");

                    b.Navigation("PostViews");

                    b.Navigation("SavedPosts");

                    b.Navigation("UserPosts");
                });

            modelBuilder.Entity("SocialMedia.Data.Models.React", b =>
                {
                    b.Navigation("PostReacts");

                    b.Navigation("SpecialCommentReacts");

                    b.Navigation("SpecialPostReacts");
                });

            modelBuilder.Entity("SocialMedia.Data.Models.ReactPolicy", b =>
                {
                    b.Navigation("Posts");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("SocialMedia.Data.Models.UserSavedPostsFolders", b =>
                {
                    b.Navigation("SavedPosts");
                });
#pragma warning restore 612, 618
        }
    }
}
